spring.application.name=skill-7-exp
spring.jpa.hibernate.ddl-auto=update
spring.datasource.dbcp2.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/skills
spring.datasource.username=root
spring.datasource.password=KANHAIYA_413k
spring.jpa.show-sql=true
